import { useEffect, useRef } from 'react';
import gsap from 'gsap';
import GrowthIcon from '../../assets/growth.svg?react';
import '../../styles/Landingpage Styles/About.css';
import aboutImg from '../../assets/about-img.png'

export default function About() {
  const aboutRef = useRef(null);

  useEffect(() => {
    const aboutSection = aboutRef.current;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            gsap.fromTo(
              ".about-title span",
              { opacity: 0, y: -20 },
              { opacity: 1, y: 0, duration: 1, stagger: 0.15, ease: "power3.out" }
            );

            gsap.fromTo(
              ".about-list",
              { opacity: 0, y: 50 },
              { opacity: 1, y: 20, duration: 1, delay: 0.5, ease: "power3.out" }
            );

            gsap.fromTo(
              ".about-img",
              {
                opacity: 0,
                y: 200,
              },
              {
                opacity: 0.25,
                y: 0,
                duration: 1,
                ease: 'power3.out',
              }
            );

          } else {
            gsap.set(".about-title span", { opacity: 0, y: -20 });
            gsap.set(".about-list", { opacity: 0, y: 130 });
            gsap.set(
              ".about-img",
              {
                opacity: 0,
                y: 100,
                duration: 0.8,
                ease: 'power3.in',
              }
            );
          }
        });
      },
      { threshold: 0.3 } 
    );

    observer.observe(aboutSection);

    return () => {
      observer.disconnect();
    };
  }, []);

  return (
    <section className="about column" id='about' ref={aboutRef}>
      <h1>About Us</h1>
      <div className="about-content">

        <div className="about-img">
          <img src={aboutImg} alt="about-us-img" />
        </div>

        <h2 className="about-title">
          <span>Empowering</span> 
          <span>Your</span> 
          <span>Career</span> 
          <span><GrowthIcon className="icon" /> </span>
          <span>with</span> 
          <span>AI</span>
        </h2>

        <div class="about-description">

          <p>
          Our intelligent platform tailors a personalized career roadmap just for you, helping you discover the best opportunities aligned with your skills, passions, and goals. Whether you're a student, a job seeker, or a professional looking to upskill, our AI-powered system ensures you’re always on the right path to success.
          </p>

          
          <div class="about-list">
            <div class="about-item">
              <span class="icon">🤖</span>
              <span>AI-Powered Recommendations: </span><br />
              Get personalized career paths, skills assessments, and learning resources—all generated by advanced AI tailored to your profile.
            </div>

            <div class="about-item">
              <span class="icon">📊</span>
              <span>Real-Time Skill Gap Analysis: </span><br />
              Instantly compare your current skill set with industry demands and close the gap with actionable suggestions.
            </div>

            <div class="about-item">
              <span class="icon">🗺️</span>
              <span>Visual Career Roadmaps: </span><br />
              See your journey mapped out clearly—from your current stage to your dream role, with each step and milestone outlined.
            </div>

            <div class="about-item">
              <span class="icon">💼</span>
              <span>Job Market Insights:</span><br />
              Discover the most in-demand roles, growing industries, and salary trends to make informed career choices.
            </div>
            <div class="about-item">
              <span class="icon">🧭</span>
              <span>AI-Personalized Career Path:</span><br />
              Unlock a tailored career journey that evolves with you—based on your goals, strengths, interests, and learning preferences.
            </div>
          </div>
        </div>
        
      </div>
    </section>
  );
}
